### ISSUE TITLE
data problem

### ISSUE THREAD

**Issue by chuanruihu** [alishdipani/U-net-Pytorch#1]
Hi , I am very interested in your work. I clone your code and read your paper, but I found your data folder is only 3 iamges , but your paper said that has 600 images. I want to konw where can get your data. Thank you.

**Comment by alishdipani** [comment]
Hey, thanks for your interest. 
The dataset is publicly available and was for a Kaggle competition [Click Here](https://www.kaggle.com/c/data-science-bowl-2018/data), I have used the stage 1 data from this competition.
Thank You.

**Comment by chuanruihu** [comment]
hi,,thank you. In your paper, I cann't find the evaluation criterion  like IOU, I suggest you if to performance your experiment results in a direct manner.

**Comment by alishdipani** [comment]
Hey, Unfortunately there isn't any evaluation metric for this dataset but I'll be testing the model on some standard dataset soon, you're free to test the model on other datasets.
Thank You.

**Comment by chuanruihu** [comment]
The  U-Net   paper's equation(2) indicated to add the cell boundary,    where is your code to perform equation(2) . Thank you!!

**Comment by alishdipani** [comment]
Hey, I have derived my model from U-net and so I have changed/dropped/added new features in the model. I have not added the cell boundary and so it's not present.
Thank You.
